import { AIAgent, SpendRequest } from '@/types';

export interface WorkspaceConfig {
  name: string;
  plan: string;
  agentCount: number;
  todaySpend: number;
  monthlySpend: number;
  monthlyCap: number;
  blockedRequestsCount: number;
  pendingApprovalsCount: number;
  velocityTrend: { day: string; spend: number }[];
  departmentBreakdown: { name: string; value: number; color: string }[];
  agents: AIAgent[];
}

export const WORKSPACE_PRESETS: Record<string, WorkspaceConfig> = {
  'TechNova Inc.': {
    name: 'TechNova Inc.',
    plan: 'Enterprise',
    agentCount: 12,
    todaySpend: 293.56,
    monthlySpend: 19105.56,
    monthlyCap: 42300.00,
    blockedRequestsCount: 1,
    pendingApprovalsCount: 6,
    velocityTrend: [
      { day: 'Mon', spend: 9500 },
      { day: 'Tue', spend: 16800 },
      { day: 'Wed', spend: 14200 },
      { day: 'Thu', spend: 27500 },
      { day: 'Fri', spend: 19800 },
      { day: 'Sat', spend: 8400 },
      { day: 'Today', spend: 293.56 },
    ],
    departmentBreakdown: [
      { name: 'Marketing', value: 7480.2, color: '#2563eb' },
      { name: 'Coding', value: 11920.36, color: '#10b981' },
      { name: 'Travel', value: 3450, color: '#f59e0b' },
      { name: 'Research', value: 710, color: '#8b5cf6' },
      { name: 'HR', value: 145, color: '#ec4899' },
      { name: 'Finance', value: 12400, color: '#06b6d4' },
    ],
    agents: [
      {
        id: 'tn-01',
        name: 'Growth Marketing Agent',
        department: 'Marketing',
        owner: 'Sarah Connor',
        dailyBudget: 4000,
        monthlyBudget: 100000,
        currentSpendToday: 1480.50,
        currentSpendMonth: 38400,
        riskLevel: 'Medium',
        allowedAPIs: ['DALL-E 3', 'Midjourney API', 'OpenAI GPT-4o'],
        status: 'active',
        totalRequests: 142,
        createdAt: '2026-07-15T09:00:00Z',
      },
      {
        id: 'tn-02',
        name: 'Autocode Sentinel',
        department: 'Coding',
        owner: 'Alex Rivera',
        dailyBudget: 12000,
        monthlyBudget: 300000,
        currentSpendToday: 3360,
        currentSpendMonth: 151200,
        riskLevel: 'Low',
        allowedAPIs: ['OpenRouter', 'Gemini Flash', 'Anthropic Claude 3.5'],
        status: 'active',
        totalRequests: 890,
        createdAt: '2026-07-10T14:30:00Z',
      },
      {
        id: 'tn-03',
        name: 'Corporate Travel Agent',
        department: 'Travel',
        owner: 'David Kim',
        dailyBudget: 40000,
        monthlyBudget: 800000,
        currentSpendToday: 0,
        currentSpendMonth: 276000,
        riskLevel: 'High',
        allowedAPIs: ['Amadeus API', 'Expedia Partner Network'],
        status: 'active',
        totalRequests: 34,
        createdAt: '2026-07-18T11:15:00Z',
      },
      {
        id: 'tn-04',
        name: 'Deep Research Agent',
        department: 'Research',
        owner: 'Elena Rostova',
        dailyBudget: 6500,
        monthlyBudget: 160000,
        currentSpendToday: 990.40,
        currentSpendMonth: 56800,
        riskLevel: 'Low',
        allowedAPIs: ['Perplexity Pro API', 'Semantic Scholar API'],
        status: 'active',
        totalRequests: 215,
        createdAt: '2026-07-20T08:00:00Z',
      },
    ],
  },

  'TravelEase Global': {
    name: 'TravelEase Global',
    plan: 'Growth',
    agentCount: 8,
    todaySpend: 1420.80,
    monthlySpend: 64800.00,
    monthlyCap: 120000.00,
    blockedRequestsCount: 4,
    pendingApprovalsCount: 2,
    velocityTrend: [
      { day: 'Mon', spend: 14000 },
      { day: 'Tue', spend: 28000 },
      { day: 'Wed', spend: 45000 },
      { day: 'Thu', spend: 32000 },
      { day: 'Fri', spend: 21000 },
      { day: 'Sat', spend: 11000 },
      { day: 'Today', spend: 1420.80 },
    ],
    departmentBreakdown: [
      { name: 'Flight Ops', value: 38500, color: '#06b6d4' },
      { name: 'Hotel Booking', value: 18200, color: '#f59e0b' },
      { name: 'Transport AI', value: 6100, color: '#10b981' },
      { name: 'Customer Concierge', value: 2000, color: '#8b5cf6' },
    ],
    agents: [
      {
        id: 'tg-01',
        name: 'Amadeus Flight Dispatcher Bot',
        department: 'Flight Ops',
        owner: 'Marcus Vance (VP Logistics)',
        dailyBudget: 15000,
        monthlyBudget: 400000,
        currentSpendToday: 8200,
        currentSpendMonth: 210000,
        riskLevel: 'High',
        allowedAPIs: ['Amadeus GDS API', 'Sabre Travel Network', 'FlightAware'],
        status: 'active',
        totalRequests: 480,
        createdAt: '2026-06-01T10:00:00Z',
      },
      {
        id: 'tg-02',
        name: 'Hotel Concierge Matcher',
        department: 'Hotel Booking',
        owner: 'Priya Sharma (Global Travel Lead)',
        dailyBudget: 8000,
        monthlyBudget: 200000,
        currentSpendToday: 3400,
        currentSpendMonth: 94000,
        riskLevel: 'Medium',
        allowedAPIs: ['Expedia API', 'Booking.com Enterprise API'],
        status: 'active',
        totalRequests: 310,
        createdAt: '2026-06-05T12:00:00Z',
      },
      {
        id: 'tg-03',
        name: 'VIP Chauffeur Dispatch AI',
        department: 'Transport AI',
        owner: 'Liam O\'Connor (Ground Ops)',
        dailyBudget: 5000,
        monthlyBudget: 120000,
        currentSpendToday: 1200,
        currentSpendMonth: 48000,
        riskLevel: 'Low',
        allowedAPIs: ['Uber Business API', 'Lyft Fleet Manager'],
        status: 'active',
        totalRequests: 190,
        createdAt: '2026-06-10T15:00:00Z',
      },
    ],
  },

  'ShopSphere AI': {
    name: 'ShopSphere AI',
    plan: 'Enterprise',
    agentCount: 18,
    todaySpend: 4890.30,
    monthlySpend: 182400.00,
    monthlyCap: 350000.00,
    blockedRequestsCount: 9,
    pendingApprovalsCount: 12,
    velocityTrend: [
      { day: 'Mon', spend: 32000 },
      { day: 'Tue', spend: 58000 },
      { day: 'Wed', spend: 72000 },
      { day: 'Thu', spend: 84000 },
      { day: 'Fri', spend: 95000 },
      { day: 'Sat', spend: 41000 },
      { day: 'Today', spend: 4890.30 },
    ],
    departmentBreakdown: [
      { name: 'Ad Bidding AI', value: 84000, color: '#ec4899' },
      { name: 'Dynamic Pricing', value: 46000, color: '#2563eb' },
      { name: 'Inventory Replenish', value: 34000, color: '#10b981' },
      { name: 'Copywriting AI', value: 18400, color: '#f59e0b' },
    ],
    agents: [
      {
        id: 'ss-01',
        name: 'Real-time Ad Bidder Bot',
        department: 'Ad Bidding AI',
        owner: 'Jason Hayes (CMO)',
        dailyBudget: 50000,
        monthlyBudget: 1200000,
        currentSpendToday: 18400,
        currentSpendMonth: 540000,
        riskLevel: 'High',
        allowedAPIs: ['Google Ads API', 'Meta Ads Manager API', 'TikTok Marketing API'],
        status: 'active',
        totalRequests: 1840,
        createdAt: '2026-05-12T09:00:00Z',
      },
      {
        id: 'ss-02',
        name: 'Dynamic Pricing Engine',
        department: 'Dynamic Pricing',
        owner: 'Chloe Bennett (Head of Commerce)',
        dailyBudget: 25000,
        monthlyBudget: 600000,
        currentSpendToday: 9200,
        currentSpendMonth: 280000,
        riskLevel: 'Medium',
        allowedAPIs: ['Shopify Plus API', 'Stripe Payments API'],
        status: 'active',
        totalRequests: 1290,
        createdAt: '2026-05-14T11:30:00Z',
      },
      {
        id: 'ss-03',
        name: 'Product Catalog Generator',
        department: 'Copywriting AI',
        owner: 'Rachel Zane (Content Lead)',
        dailyBudget: 8000,
        monthlyBudget: 150000,
        currentSpendToday: 2100,
        currentSpendMonth: 64000,
        riskLevel: 'Low',
        allowedAPIs: ['Midjourney API', 'OpenAI DALL-E 3', 'Gemini Flash'],
        status: 'active',
        totalRequests: 640,
        createdAt: '2026-05-18T14:00:00Z',
      },
    ],
  },

  'HealthAI MedTech': {
    name: 'HealthAI MedTech',
    plan: 'Custom HIPAA',
    agentCount: 5,
    todaySpend: 85.00,
    monthlySpend: 12400.00,
    monthlyCap: 80000.00,
    blockedRequestsCount: 0,
    pendingApprovalsCount: 1,
    velocityTrend: [
      { day: 'Mon', spend: 3200 },
      { day: 'Tue', spend: 18000 },
      { day: 'Wed', spend: 8400 },
      { day: 'Thu', spend: 12000 },
      { day: 'Fri', spend: 9500 },
      { day: 'Sat', spend: 2100 },
      { day: 'Today', spend: 85.00 },
    ],
    departmentBreakdown: [
      { name: 'HIPAA Sanitizer', value: 6800, color: '#10b981' },
      { name: 'Trial Finder', value: 3400, color: '#2563eb' },
      { name: 'Lab Parser', value: 2200, color: '#8b5cf6' },
    ],
    agents: [
      {
        id: 'hm-01',
        name: 'PHI De-identification Guard',
        department: 'HIPAA Sanitizer',
        owner: 'Dr. Aris Thorne (Chief Compliance)',
        dailyBudget: 2000,
        monthlyBudget: 50000,
        currentSpendToday: 450,
        currentSpendMonth: 18400,
        riskLevel: 'Low',
        allowedAPIs: ['Google Healthcare NLP API', 'AWS Medical Comprehend'],
        status: 'active',
        totalRequests: 420,
        createdAt: '2026-04-01T08:00:00Z',
      },
      {
        id: 'hm-02',
        name: 'Clinical Trial Patient Matcher',
        department: 'Trial Finder',
        owner: 'Dr. Evelyn Reed (Research Chair)',
        dailyBudget: 4000,
        monthlyBudget: 100000,
        currentSpendToday: 950,
        currentSpendMonth: 32000,
        riskLevel: 'Medium',
        allowedAPIs: ['ClinicalTrials.gov APIv2', 'PubMed BioC API'],
        status: 'active',
        totalRequests: 210,
        createdAt: '2026-04-05T10:00:00Z',
      },
    ],
  },
};
